#!/bin/bash

# original by N4IRS 07/26/2017
# mod4whip by N8THN
# contributor: KM4NNO
# V1.2 Dec 31 , 2020
#release date 20201231-1

do_check_if_firsttime() {
if [ -e /etc/asterisk/firsttime ]; then
return
else
exit 0
fi
}

do_is_root() {
if [ `whoami` != root ]; then
        whiptail --msgbox "This script must be run as root or with sudo." 20 60 2
    exit 1
fi
}


do_set_root_passwd() {
ANSWER=1
        if (whiptail --title "Set Root password" --yesno " \
        \nFor increased security it is recommended not to set the root password \
	\n\nThe root login is disabled for SSH and CONSOLE login by defualt \
        \nBy setting the root password you will allow root to login via the console \
        \nWould you like to set the root password?" --defaultno 20 80) then
         ANSWER=$?
        fi
        if [ "$ANSWER" = "0" ]; then    # answered yes
                while ! passwd root
                do
                        whiptail --msgbox "ERROR: A valid password must be assigned to continue" 20 80 2
                done
        fi
}

do_set_mypasswd() {
        REALID=$(who am i | awk '{print $1}')
        whiptail --title "User: $REALID password" --msgbox \
	"Welcome to PTTLink first-time setup \
        \nThis script will walk you through a few \
	\nof the basic system setup options \
        \n\nFor system security we will change the password from \
        \nthe default password included in the image \
        \nWe will do this now.\n\nUser: $REALID" 20 80 2
        clear
                while ! passwd $REALID
                do
                        whiptail --msgbox "ERROR: Password does not match" 10 80 2
                        clear
                done
        whiptail --msgbox "Password successfully changed" 10 60 2
}

do_set_timezone() {
                        whiptail --msgbox "By default, the time zone is set to: $(cat /etc/timezone) \
			\nA correct time zone entry will allow the \
			\nsystem clock to report the correct time" 10 80 2
                        dpkg-reconfigure tzdata
}

do_set_host() {
                if [ -x /usr/local/sbin/set-host ]; then
                        whiptail --msgbox "By default, the host name is set to: $(cat /etc/hostname) \
			\nThe host name should be set to something meaningful \
			\n(i.e. the location of this system)" 10 80 2
                        /usr/local/sbin/set-host
                fi
}

do_net_setup() {
                if [ -x /usr/local/sbin/net-setup ]; then
                        whiptail --msgbox "You may now configure system networking \
			\neither a static or DHCP (dynamic) address \
			\n\nIf you choose static addressing, you will need \
			\nto have the following information ready: \
			\nIP ADDRESS, NETMASK, DEFAULT GATEWAY, \
			\nPRIMARY DNS, and SECONDARY DNS" 20 80 2
                        /usr/local/sbin/net-setup
                fi
}

do_node_setup() {
                if [ -x /usr/local/sbin/node-setup ]; then
                        whiptail --msgbox "You will now move on to \
			the PTTLink node setup program for PTTLink" 10 80 2
			/usr/local/sbin/node-setup
                fi
}

do_fs_resize() {
                if [ -x /usr/local/sbin/fs_resize ]; then
                        echo ""
                        echo "You can now resize the root partition"
                        echo "to fill the available disk space"
                        echo ""
                        /usr/local/sbin/fs_resize
                fi
}

do_finish() {
                whiptail --msgbox "Setup is complete.\nWe will reboot once you click <OK>" 20 80 2
                rm /etc/asterisk/firsttime
                sync
                sleep 1
                reboot
}


do_check_if_firsttime
do_is_root
do_set_mypasswd
do_set_root_passwd
do_set_timezone
do_set_host
do_net_setup
do_node_setup
do_finish


